[package]
name = "even_more_pizza"
version = "0.1.0"
authors = ["Furqan Ahmed <nblogist1@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
num-format = "0.4.0"
simple-error = "0.2.1"
